# Generated by Django 4.0.4 on 2022-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
