# Generated by Django 4.0.4 on 2022-05-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_message_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='senderID',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
