# Generated by Django 4.0.4 on 2022-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_senderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ownedByCurrentUser',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
