# Generated by Django 4.0.4 on 2022-05-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_ownedbycurrentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ownedByCurrentUser',
        ),
        migrations.RemoveField(
            model_name='message',
            name='senderID',
        ),
    ]
