# Generated by Django 4.0.4 on 2022-05-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_age_profile_description_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='real_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
