# Generated by Django 4.0.4 on 2022-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='real_avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='profile',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
