# Generated by Django 4.0.4 on 2022-05-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_profile_revealed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='first_member_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='second_member_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
