# Generated by Django 4.0.4 on 2022-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reason',
            field=models.CharField(blank=True, choices=[('to meet friends', 'to meet friends'), ('to kill time', 'to kill time'), ('to test out the chat app', 'to test out the chat app'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
