# Generated by Django 4.0.4 on 2022-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_profile_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='real_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
