# Generated by Django 4.0.4 on 2022-08-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_profile_is_online_alter_profile_real_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='real_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
